### ISSUE TITLE
On FF57 click to copy works but click action occurs

### ISSUE THREAD

**Issue by ghost** [trembacz/xpath-finder#1]
First of all, its really nice plugin. I was looking for something similar after FF upgraded to 55+ and had only support for webextentions. I was using firebug+Firepath earlier and missed it. 

Environment: 
FF version: 57.0.1 64bit
OS: Ubuntu 16.04 LTS

I started plugin using `web-ext run` to try the plugin.
Steps:
1. Click on the plugin icon, cursor will be changed to the **crosshair**
1. Hover over the desired element **(elements are highlighted on hover)**
1. Xpath is seen at bottom left on page.
1. Click to clickable href link element to copy xpath. xpath copied to clipboard. 
1. Click action leads to new page which was linked in href. This happens for all clickable elements where action or change of view is involved. Browser navigates to new page.

Expected:
1. Browser should not navigate to new page.
1. User should be able to copy xpath for href elements without actually need to go on those hrefs. Its the way it was in firepath and looks more sensible to have.

PS: I am new to github project so feel free to correct me. I will try to figure out but javascript isn't my expertise. I can surely help with testing. :)

**Comment by trembacz** [comment]
Hey @yummuy 
Thanks for info, version 0.93 of the plugin should be already available, please update add-on and let me know if this works fine for you now. Thanks

**Comment by ghost** [comment]
Thanks for fix. Tested OK and works as expected! :)
