### ISSUE TITLE
FF 52.1.0 button changes back to inactive mode

### ISSUE THREAD

**Issue by GreenLunar** [trembacz/xpath-finder#2]
xpath-finder may be active sometimes, but for a fraction of a second.

**Comment by trembacz** [comment]
Hey, sorry but I can't reproduce this issue. Could you try to disable other extensions and try again or just let me know which extensions you are using and I will try to reproduce. Thanks

**Comment by GreenLunar** [comment]
I use FF on Linux. I'll disable some extensions and see if doing so would work for me.

**Comment by GreenLunar** [comment]
It's working.
Maybe it was the ePUB reader that caused it.
