### ISSUE TITLE
Idea: add keyboard shortcut for enabling/disabling extension

### ISSUE THREAD

**Issue by nicola-zanardi** [trembacz/xpath-finder#5]
First of all many thanks for the extension, very useful for writing Selenium automation!

I would like to propose a small improvement: it would be nice to be able to toggle the extension on or off via a keyboard shortcut that can be set in the extension configuration page. That would save some mouse clicks!

Thanks,

Galactic Dessert

**Comment by ccpwcn** [comment]
Yes, It's useful for some action, such as I want to check loading on some web pages, the loading show and hidden action is very quickly, use mouse click enable and disable is very slowly, the keyboard shortcut can resolve this problem.

**Comment by trembacz** [comment]
@galacticdessert, @ccpwcn sorry for late reply.. I've added a feature to enable/disable extension by keyboard shortcut. It's fully available for Firefox version of extension and partially for Chrome (shortcut works but you can't edit it, Chrome doesn't support this). I've already uploaded new version so it should be available to update soon.

![image](https://user-images.githubusercontent.com/4508357/48665993-6fc79400-eab9-11e8-8b10-9427b5a517da.png)

**Comment by nicola-zanardi** [comment]
Thanks!!
